### ISSUE TITLE
Request: webtrees 2.x addon

### ISSUE THREAD

**Issue by mrqd9** [PeWu/topola-webtrees#7] opened 2021-01-10 07:52 UTC
Hello @PeWu
Is there any hope for us to get a topola-viewer module for webtrees 2.x ?

**Comment by PeWu** [comment] 2021-01-12 23:04
Duplicate of #2

**Comment by WirelessMind** [comment] 2021-02-17 11:55
I have never developed any module for webtrees and this is the first time I see its source...

Adding that module in webtrees 2, the first error is missing abstract classes.
I put them in the module.php: the error is gone and the site loads, but the module does not appear in the control panel or even in the menu.
```
    /**
     * CSS class for the URL.
     *
     * @return string
     */
    public function chartMenuClass(): string
    {
        return null; //'menu-chart-topola'; //commented because there is no css for this module
    }

    /*
     * Return a menu item for this chart - for use in individual boxes.
     *
     * @param Individual $individual
     *
     * @return Menu|null
     */
    public function chartBoxMenu(Individual $individual): ?Menu
    {
        return $this->chartMenu($individual);
    }
 
    /**
     * The title for a specific instance of this chart.
     *
     * @param Individual $individual
     *
     * @return string
     */
    public function chartTitle(Individual $individual): string
    {
        return I18N::translate('Interactive tree (Topola):  %s', $individual->fullName());
    }
 
    /**
     * A form to request the chart parameters.
     *
     * @param Individual $individual
     * @param mixed[]    $parameters
     *
     * @return string
     */
    public function chartUrl(Individual $individual, array $parameters = []): string
    {
        return route(static::class, [
                'xref' => $individual->xref(),
                'tree' => $individual->tree()->name(),
            ] + $parameters + self::DEFAULT_PARAMETERS);
    }

    public function chartUrlAttributes(): array
    {
    }

  public function chartMenu(Individual $individual): Menu {
    return new Menu(
            $this->getChartTitle("Interactive tree (Topola)"),
            $this->chartUrl($individual),
            $this->chartMenuClass(),
            $this->chartUrlAttributes()
    );
  }

```

I don't know if it's because I left the "chartUrlAttributes()" function empty, but I don't know what to do with this.

Has anyone tried updating it for version 2?

Thanks

**Comment by WirelessMind** [comment] 2021-02-18 16:00
Anyone know how to update it for version 2?
Please :(

**Closed** 2021-05-30 07:18 UTC
